const ImagePath = {
  BLUE_LOGO: "/IS_Logo_Blue.webp",
  WHITE_LOGO: "/IS_Logo_White.webp",
  GOOGLE_RATING: "/google_rating.png",
  TRUSTPILOT_RATING: "/trustpilot_rating.png",
  GOOGLE_RATING_BLACK: "/google_rating_black.webp",
  TRUSTPILOT_RATING_BLACK: "/trustpilot_rating_black.webp",
  HERO_IMAGE: "/Hero_img.webp",
  CITY_VECTOR: "/city_vector.svg",
  STATE_VECTOR: "/state_vector.svg",
  COUNTRY_VECTOR: "/country_vector.svg",
  BENEFITS_IMAGE: "/benefits_img.webp",
  TICK_VECTOR: "/tick_vector.svg",
  ENROLMENT_PARTNER: "/enrolment_partner.png",
  REGISTER_IMAGE: "/register_img.webp",
  TICK_WHITE_VECTOR: "/tick_white_vector.svg",
  QUOTE_ICON: "/quote_icon.svg",
  ABOUT_IMAGE: "/about-image.webp",
};
export default ImagePath;
